### ISSUE TITLE
tests/input1Ref.sam is missing

### ISSUE THREAD

**Issue by vadimzalunin** [benedictpaten/marginAlign#8]
# 
## FAIL: testMarginCaller1Ref (**main**.TestCase)

Traceback (most recent call last):
  File "tests/tests.py", line 64, in testMarginCaller1Ref
    self.validateSam("./tests/input1Ref.sam")
  File "tests/tests.py", line 26, in validateSam
    self.assertTrue(os.path.isfile(samFile))
AssertionError: False is not true
# 
## FAIL: testMarginCallerNoMarginalize1Ref (**main**.TestCase)

Traceback (most recent call last):
  File "tests/tests.py", line 71, in testMarginCallerNoMarginalize1Ref
    self.validateSam("./tests/input1Ref.sam")
  File "tests/tests.py", line 26, in validateSam
    self.assertTrue(os.path.isfile(samFile))
AssertionError: False is not true

**Comment by mitenjain** [comment]
Resolved. The file went (accidentally) missing.
